site_name: sinq
site_description: Concurrent integration and end-to-end HTTP testing tool for stateful workflows.
site_url: https://sinq.veitangie.dev

theme:
  name: material
  icon:
    logo: material/api
  palette:
    - scheme: slate
      primary: custom
      accent: cyan
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

repo_name: Veitangie/sinq
repo_url: https://github.com/Veitangie/sinq

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Lua API: lua-api.md
  - Scenarios & Config: scenario.md
  - Environment Matrix: env-matrix.md
  - Architecture & Components:
    - Overview: overview.md
    - Treewalker: treewalker.md
    - Execution Runner: runner.md
  - CI/CD Integration: ci-cd-integration.md
  - Additional Information:
    - Alternatives & Comparisons: alternatives.md
    - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
